# Generated by Django 4.2.3 on 2023-07-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_offficer',
            new_name='is_officer',
        ),
    ]
