# Generated by Django 4.2.3 on 2023-07-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle_assignment', '0002_alter_driver_avaialabilty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='avaialabilty',
        ),
    ]
