# Generated by Django 4.2.3 on 2023-07-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle_assignment', '0004_delete_servicedescription_alter_companyinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
