# Generated by Django 4.2.3 on 2023-07-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle_assignment', '0006_rename_vehicle_license_number_driver_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='registry',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vehicle_assignment.driver'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vehicle_assignment.employee'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vehicle_assignment.officer'),
        ),
    ]
