# Generated by Django 4.2.3 on 2023-07-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle_assignment', '0010_employeereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
